apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: banking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: gcr.io/cloud-computing-488905/customer-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql.banking-app.svc.cluster.local:3306/bankingdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: banking-app
spec:
  selector:
    app: customer-service
  ports:
    - port: 8082
